export enum ActionTypes {
	SET_THOUGHTS = 'SET_THOUGHTS',
	ADD_THOUGHT = 'ADD_THOUGHT',
	DELETE_THOUGHT = 'DELETE_THOUGHT',
	SET_CURRENT_THOUGHT = 'SET_CURRENT_THOUGHT',
	EDIT_THOUGHT = 'EDIT_THOUGHT',
}
